---
# This file is meant to be also used by upgrade playbook

- name: Install elasticsearch-curator package
  apt:
    deb: "{{ repository_url }}/files/{{ curator_package.filename.Debian }}"
    state: present
  register: result
  retries: 60
  delay: 30
  until: result is succeeded
