---
trigger: none

resources:
  pipelines:
    - pipeline: _epiphany-platform.epiphany [build]
      source: yaml-pipelines\epiphany-platform.epiphany [build]

stages:
- stage: Deploy
  jobs:
    - job: Deploy
      pool:
        name: Az Docker Build
      steps:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Pipeline Artifact'
          inputs:
            buildType: 'specific'
            project: 'epiphany'
            definition: 142
        - task: Bash@3
          displayName: Print BuildId
          inputs:
            targetType: inline
            script: |
              echo $(Build.BuildId)
